@baseurl=http://localhost:8080

GET {{baseurl}}/ping

###

GET {{baseurl}}/api/v1/test

###

GET {{baseurl}}/api/v1/campaign

###
POST {{baseurl}}/api/v1/campaign
Content-Type: application/json

{
  "name": "Test Campaign",
  "description": "This is a test campaign",
  "startDate": "2023-10-01T00:00:00Z",
  "endDate": "2023-10-31T23:59:59Z"
}
###
