@baseurl=http://localhost:8080

GET {{baseurl}}/ping

###

GET {{baseurl}}/api/v1/test

###

GET {{baseurl}}/api/v1/campaign

###
GET {{baseurl}}/api/v1/campaign/d17gr1lroejs1qbe7700

###
POST {{baseurl}}/api/v1/campaign
Content-Type: application/json

{
  "title": "Test Campaign 3",
  "content": "This is a test campaign 3",
  "emails": ["joao@test.com", "jonny@test.com"]
}
###
