@baseurl=http://localhost:8080
@identityurl=http://localhost:8070

GET {{baseurl}}/ping

###

GET {{baseurl}}/api/v1/test

###

GET {{baseurl}}/api/v1/campaign
Authorization: Bearer {{access_token}}

###
GET {{baseurl}}/api/v1/campaign/{{campaignId}}
Authorization: Bearer {{access_token}}

###
# @name create_campaign
POST {{baseurl}}/api/v1/campaign
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "Test Campaign 3",
  "content": "This is a test campaign 3",
  "emails": ["joao@test.com", "jonny@test.com"]
}
###
@campaignId = {{create_campaign.response.body.campaign_id}}

# client password flow (user credentials) 
# @name token
POST {{identityurl}}/realms/dummy-provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=notifysystem&username=vitaodemolay&password=passw0rd&grant_type=password
###
@access_token = {{token.response.body.access_token}}










# client credentials flow (M2M)
POST {{identityurl}}/realms/dummy-provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=notifysystem&client_secret=KwNAiZQFYxNbjSj3mkcDztubgokhCPS2&grant_type=client_credentials
###
