// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vitaodemolay/notifsystem/internal/domain/repository/campaign (interfaces: CampaignRepository)
//
// Generated by this command:
//
//	mockgen -package=mock -destination=./mock/campaign.go . CampaignRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	campaign "github.com/vitaodemolay/notifsystem/internal/domain/model/campaign"
	gomock "go.uber.org/mock/gomock"
)

// MockCampaignRepository is a mock of CampaignRepository interface.
type MockCampaignRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignRepositoryMockRecorder
	isgomock struct{}
}

// MockCampaignRepositoryMockRecorder is the mock recorder for MockCampaignRepository.
type MockCampaignRepositoryMockRecorder struct {
	mock *MockCampaignRepository
}

// NewMockCampaignRepository creates a new mock instance.
func NewMockCampaignRepository(ctrl *gomock.Controller) *MockCampaignRepository {
	mock := &MockCampaignRepository{ctrl: ctrl}
	mock.recorder = &MockCampaignRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignRepository) EXPECT() *MockCampaignRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockCampaignRepository) FindAll() ([]campaign.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]campaign.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCampaignRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCampaignRepository)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockCampaignRepository) FindByID(id string) (*campaign.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*campaign.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCampaignRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCampaignRepository)(nil).FindByID), id)
}

// Save mocks base method.
func (m *MockCampaignRepository) Save(arg0 *campaign.Campaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCampaignRepositoryMockRecorder) Save(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCampaignRepository)(nil).Save), arg0)
}
